// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-redesign/AdminDashboard.tsx": () => import("../components/mockups/chat-redesign/AdminDashboard.tsx"),
  "./components/mockups/chat-redesign/AgentWorkspace.tsx": () => import("../components/mockups/chat-redesign/AgentWorkspace.tsx"),
  "./components/mockups/chat-redesign/UserChat.tsx": () => import("../components/mockups/chat-redesign/UserChat.tsx")
};
